"""Generate the hybrid reference docs from a probe file + the toolset->domain map.

Inputs:
  - probes/<X.Y.Z>.json      raw probe dump (one per Epic release; keyed by full version)
  - scripts/toolset_map.yaml curated toolset -> domain map (shared across engine versions)

Outputs (all under skills/ue-official-mcp-<X.Y>/references/, regenerated from scratch each run):
  - toolsets/<Name>.md       raw per-toolset catalog with full schemas (source of truth)
  - toolsets/index.md        raw catalog index
  - <domain>.md              curated, domain-grouped summaries that link into the raw files
  - uncategorized.md         toolsets the server reported but the map doesn't place
  - index.md                 reference hub with live counts + probe stamp

Deterministic: everything is sorted, and the only timestamp comes from the probe's
`probed_at`, so regenerating from the same probe yields byte-identical output.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

from . import paths

_DO_NOT_EDIT = (
    "do not hand-edit — regenerated by `ue-mcp-skills sync`; "
    "edit scripts/toolset_map.yaml to change grouping"
)


def _header(cache: dict) -> str:
    server = cache.get("server") or {}
    name = server.get("name") or "unknown"
    version = server.get("version") or ""
    probed = cache.get("probed_at") or "(unknown time)"
    return f"<!-- GENERATED ({_DO_NOT_EDIT}). server: {name} {version}; probed: {probed} -->"


def _cell(text: str | None, limit: int = 200) -> str:
    """Sanitize a string for a single Markdown table cell."""
    if not text:
        return ""
    line = text.strip().splitlines()[0].strip() if text.strip() else ""
    line = line.replace("|", "\\|")
    if len(line) > limit:
        line = line[: limit - 1].rstrip() + "…"
    return line


def _fmt_schema(schema) -> str:
    if not schema:
        return "_(no schema)_"
    body = json.dumps(schema, indent=2, ensure_ascii=False, sort_keys=True)
    return "```json\n" + body + "\n```"


def _write(path: Path, blocks: list[str]) -> None:
    path.write_text("\n\n".join(b for b in blocks if b is not None) + "\n", encoding="utf-8")


def _raw_filename(toolset_name: str) -> str:
    return f"{toolset_name}.md"


def _render_raw(toolset: dict, cache: dict) -> str:
    name = toolset.get("name", "")
    desc = (toolset.get("description") or "").strip()
    tools = sorted(toolset.get("tools", []) or [], key=lambda t: t.get("name", ""))
    blocks = [_header(cache), f"# `{name}`"]
    if desc:
        blocks.append(desc)
    blocks.append(f"**{len(tools)} tool(s).**")
    for tool in tools:
        tname = tool.get("name", "")
        tdesc = (tool.get("description") or "").strip()
        blocks.append(f"## `{tname}`")
        if tdesc:
            blocks.append(tdesc)
        blocks.append("**Input schema**\n\n" + _fmt_schema(tool.get("inputSchema")))
        if tool.get("outputSchema"):
            blocks.append("**Output schema**\n\n" + _fmt_schema(tool.get("outputSchema")))
    return "\n\n".join(blocks) + "\n"


def _render_domain(title: str, description: str, toolset_names: list[str],
                   by_name: dict, cache: dict) -> tuple[str, int, int]:
    """Return (markdown, present_toolset_count, tool_count) for a curated domain file."""
    blocks = [_header(cache), f"# {title}"]
    if description:
        blocks.append(description)

    present = [n for n in toolset_names if n in by_name]
    tool_count = sum(len(by_name[n].get("tools", []) or []) for n in present)
    blocks.append(
        f"_{len(present)} toolset(s), {tool_count} tool(s). "
        f"Full schemas in the [raw catalog](toolsets/index.md)._"
    )

    for tsname in toolset_names:
        toolset = by_name.get(tsname)
        if toolset is None:
            blocks.append(f"## `{tsname}`\n\n_Not reported by the probed server._")
            continue
        tsdesc = _cell(toolset.get("description"))
        link = f"toolsets/{_raw_filename(tsname)}"
        header = f"## `{tsname}` · [raw schemas]({link})"
        rows = ["| Tool | Summary |", "|---|---|"]
        for tool in sorted(toolset.get("tools", []) or [], key=lambda t: t.get("name", "")):
            rows.append(f"| `{tool.get('name','')}` | {_cell(tool.get('description'))} |")
        section = header
        if tsdesc:
            section += f"\n\n{tsdesc}"
        section += "\n\n" + "\n".join(rows)
        blocks.append(section)

    return "\n\n".join(blocks) + "\n", len(present), tool_count


def regenerate_from_data(data: dict, map_path: Path, engine_version: str) -> dict:
    """Regenerate all reference docs for one engine version. Returns a summary dict."""
    spec = yaml.safe_load(map_path.read_text(encoding="utf-8")) or {}
    domains = spec.get("domains") or {}

    toolsets = data.get("toolsets", []) or []
    by_name = {t.get("name", ""): t for t in toolsets}

    references_dir = paths.references_dir(engine_version)
    toolsets_dir = paths.toolsets_dir(engine_version)

    # Clean slate so removed toolsets never leave orphan files.
    references_dir.mkdir(parents=True, exist_ok=True)
    toolsets_dir.mkdir(parents=True, exist_ok=True)
    for old in list(references_dir.glob("*.md")):
        old.unlink()
    for old in list(toolsets_dir.glob("*.md")):
        old.unlink()

    # 1) Raw per-toolset files.
    for toolset in sorted(toolsets, key=lambda t: t.get("name", "")):
        fname = _raw_filename(toolset.get("name", "unnamed"))
        (toolsets_dir / fname).write_text(_render_raw(toolset, data), encoding="utf-8")

    # 2) Curated domain files + collect which toolsets got mapped.
    mapped: set[str] = set()
    domain_rows: list[tuple[str, str, int, int]] = []  # (key, title, n_toolsets, n_tools)
    for key, dom in domains.items():
        title = dom.get("title", key)
        description = dom.get("description", "")
        ts_names = list(dom.get("toolsets", []) or [])
        mapped.update(ts_names)
        md, n_ts, n_tools = _render_domain(title, description, ts_names, by_name, data)
        (references_dir / f"{key}.md").write_text(md, encoding="utf-8")
        domain_rows.append((key, title, n_ts, n_tools))

    # 3) Uncategorized: probed toolsets absent from the map.
    unmapped = sorted(n for n in by_name if n not in mapped)
    uncat_md, _, uncat_tools = _render_domain(
        "Uncategorized toolsets",
        "Toolsets reported by the server that are not yet placed in scripts/toolset_map.yaml. "
        "Add each under the right domain and re-run sync/generate." if unmapped
        else "All probed toolsets are mapped to a domain.",
        unmapped, by_name, data,
    )
    (references_dir / "uncategorized.md").write_text(uncat_md, encoding="utf-8")

    # 4) Raw catalog index.
    raw_rows = ["| Toolset | Tools | Description |", "|---|---|---|"]
    for toolset in sorted(toolsets, key=lambda t: t.get("name", "")):
        n = toolset.get("name", "")
        raw_rows.append(
            f"| [`{n}`]({_raw_filename(n)}) | {len(toolset.get('tools', []) or [])} "
            f"| {_cell(toolset.get('description'))} |"
        )
    _write(toolsets_dir / "index.md", [
        _header(data),
        "# Raw toolset catalog",
        f"{len(toolsets)} toolset(s), full schemas verbatim from `describe_toolset`.",
        "\n".join(raw_rows),
    ])

    # 5) Reference hub.
    server = data.get("server") or {}
    meta = [
        f"- **Server:** {server.get('name','unknown')} {server.get('version','')}".rstrip(),
        f"- **Engine version:** UE {engine_version}",
        f"- **Endpoint probed:** `{data.get('endpoint','')}`",
        f"- **Probed at:** {data.get('probed_at','(unknown)')}",
        f"- **Toolsets:** {len(toolsets)} · **Tools:** {data.get('tool_count', sum(len(t.get('tools',[]) or []) for t in toolsets))}",
    ]
    hub_rows = ["| Domain | Toolsets | Tools | Reference |", "|---|---|---|---|"]
    for key, title, n_ts, n_tools in domain_rows:
        hub_rows.append(f"| {title} | {n_ts} | {n_tools} | [{key}.md]({key}.md) |")
    hub_rows.append(
        f"| _Uncategorized_ | {len(unmapped)} | {uncat_tools} | "
        f"[uncategorized.md](uncategorized.md) |"
    )
    _write(references_dir / "index.md", [
        _header(data),
        f"# Official UE {engine_version} MCP — reference",
        f"Generated from a live probe of the official Unreal Engine {engine_version} "
        "ModelContextProtocol server. Pick a domain, then call directly from the per-toolset "
        "raw schemas; only `describe_toolset` if a call returns a schema-shaped error.",
        "\n".join(meta),
        "## Domains",
        "\n".join(hub_rows),
        "## Raw catalog",
        "One file per toolset with full input/output schemas: [toolsets/](toolsets/index.md).",
    ])

    # 6) Site landing page (skill-folder root). The Anthropic skill loader only
    # cares about SKILL.md + references/; this file exists purely so the mkdocs
    # site has a working `/` URL on GitHub Pages.
    tool_count = data.get("tool_count", sum(len(t.get("tools", []) or []) for t in toolsets))
    landing_blocks = [
        f"# UE Official MCP — {engine_version}",
        f"Reference catalog for the official Unreal Engine {engine_version} "
        "`ModelContextProtocol` server, captured by probing a live editor.",
        "- **[Skill](SKILL.md)** — routing layer for agents driving the editor.",
        "- **[Reference hub](references/index.md)** — per-domain tool tables.",
        "- **[Raw toolset catalog](references/toolsets/index.md)** — full JSON schemas, "
        "one file per toolset.",
        f"_{len(toolsets)} toolset(s), {tool_count} tool(s). "
        f"Probed: {data.get('probed_at','(unknown)')}._",
        "[Source on GitHub](https://github.com/tc-imba/ue-official-mcp)",
    ]
    (paths.skill_dir(engine_version) / "index.md").write_text(
        "\n\n".join(landing_blocks) + "\n", encoding="utf-8"
    )

    return {
        "engine_version": engine_version,
        "toolset_count": len(toolsets),
        "tool_count": data.get("tool_count", sum(len(t.get("tools", []) or []) for t in toolsets)),
        "domain_count": len(domain_rows),
        "unmapped": unmapped,
        "skipped_candidates": data.get("skipped_candidates", []),
    }


def regenerate_from_probe(probe_path: Path, map_path: Path, engine_version: str) -> dict:
    """Regenerate docs from a saved probe file (probes/X.Y.Z.json)."""
    data = json.loads(probe_path.read_text(encoding="utf-8"))
    return regenerate_from_data(data, map_path, engine_version)
